name: installipfs
description: install kubo

runs:
  using: "composite"
  steps:
    - name: Install kubo
      shell: bash
      run: (cd /tmp && go install github.com/ipfs/kubo/cmd/ipfs@master)
    - uses: ipfs/start-ipfs-daemon-action@v1
      with:
        args: --init --enable-pubsub-experiment
